### PR TITLE
Bugfix/taborder

### PR DESCRIPTION
**Pull request by shurst-ma**
@andrewphilipsmith @clairebyrne  please review!

### CODE REVIEW

**Comment by andrewphilipsmith** [comment]
Hi @shurst-ma You seem to have made an extra copy of `FormValidationExport.cs` and `frmExportMain.cs` in the root of the repo. Please could you check you've got all your changes in the right one and deleted the extras? Thank you.

**Comment by shurst-ma** [comment]
Grrr...
Sorry Andy.   I've attempted to recover.  As I said Git is new to me:

git clone --single-branch -b bugfix/taborder
https://github.com/mapaction/mapaction-toolbox.git
cd mapaction-toolbox/
git rm frmExportMain.cs
git rm FormValidationExport.cs
git commit -m "Removed FormValidationExport.cs and frmExportMain.cs
uploaded to wrong directory."

However, I still see the files at:
https://github.com/mapaction/mapaction-toolbox/tree/bugfix/taborder

Once this is resolved, should I create a new Pull Request?

Thanks for your support and sorry to be a pain.
Cheers,
-Steve

**Comment by andrewphilipsmith** [comment]
Hi Steve,
After the `git commit....` line a `git push` will sync it all changes back to github.com. (A commit in git happens purely locally).

Also there is no need to create a new clone each time:
* `git pull` will update your local clone from github.com
* `git checkout` can be used to switch or create new branches.
* `git status` does exactly that...

Or if you prefer... The Github Desktop GUI is pretty good in my view. It supports all the common, basic tasks that we use. The options it uses in the background tend to be very safe and stops you getting into trouble. I rarely _need_ to use the cmdline. 

I hope that helps.

**Comment by shurst-ma** [comment]
Thanks Andy.  All done now.

**Comment by shurst-ma** [comment]
Hi Andy,
After sorting those files out on the taborder branch:
https://github.com/mapaction/mapaction-toolbox/tree/bugfix/taborder

... Do I need to make a new Pull Request?

Thanks,

-Steve

**Pull request merged**
